### ISSUE TITLE
Specific date fetching returning only first page.

### ISSUE THREAD

**Issue by Luiz-N** [XOlator/wayback_gem#2]
When passing in a date parameter to the page method it only returns the very first archived page. This issue also occurs when passing in ":last" symbol.

ex:
 Wayback.page('http://www.cnn.com', '20130919035501')

**Comment by gleuch** [comment]
Thanks Luiz-N. Dates were being parsed incorrectly. Update 819e8e353aab6c5a09191438ffc60b7908a1c78c corrects this issue.

Gem updated and released as 0.2.1.
